---

name: Release notify
description: This action notify about releases
inputs:
  jira_login:
    required: true
    description: Jira login
  jira_api_key:
    required: true
    description: Jira API key
  jira_org:
    required: true
    description: Jira organization
  jira_task:
    required: true
    description: Jira task code
  slack_token:
    required: true
    description: Slack token
  slack_channel:
    required: true
    description: Slack channel

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: alert-circle
  color: blue