
name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Run URL Checker
        uses: wowvendor/release-notify-action@v1
        with:
          jira_login: m.pak@bpcbt.com
          jira_api_key: TY3Z0OyQUHLsJ2hgy7yxE12C
          jira_org: wowvendor
          jira_task: ${{ github.base_ref }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: C01T49QL4G0
          debug: true
